"""Export the trained policies for dependency-free C++ inference; no retraining."""
import argparse
import hashlib
import json
from pathlib import Path
from native import ACTIONS, FEATURES, ROOT, load_weights


def export(output):
    import torch
    from stable_baselines3 import PPO
    output.mkdir(parents=True, exist_ok=True)
    sections = ['// Generated by ai/export_policies.py; do not edit weights by hand.',
                '#pragma once', 'namespace MyGame { namespace AI { namespace Data {']

    def array(name, values, precision):
        values = list(values)
        tokens = []
        for value in values:
            token = format(float(value), '.9g' if precision == 'float' else '.17g')
            if precision == 'float':
                if '.' not in token and 'e' not in token:
                    token += '.0'
                token += 'f'
            tokens.append(token)
        sections.append(f'static const {precision} {name}[{len(tokens)}] = {{')
        sections.extend('    ' + ', '.join(tokens[i:i+8]) + ',' for i in range(0, len(tokens), 8))
        sections.append('};')

    array('CemWeights', load_weights(ROOT / 'ai/models/cem.json'), 'double')
    model = PPO.load(ROOT / 'ai/models/ppo.zip', device='cpu')
    actor = model.policy.mlp_extractor.policy_net
    assert len(actor) == 4 and isinstance(actor[1], torch.nn.Tanh) and isinstance(actor[3], torch.nn.Tanh)
    layers = [actor[0], actor[2], model.policy.action_net]
    assert [(layer.in_features, layer.out_features) for layer in layers] == [(108, 64), (64, 64), (64, 9)]
    for i, layer in enumerate(layers):
        array(f'Layer{i}Weights', layer.weight.detach().cpu().flatten(), 'float')
        array(f'Layer{i}Bias', layer.bias.detach().cpu().flatten(), 'float')
    sections.append('} } }')
    header = output / 'PolicyData.h'
    header.write_text('\n'.join(sections) + '\n')
    manifest = dict(schema=1, observation_features=FEATURES, actions=ACTIONS, layers=[108, 64, 64, 9],
                    activation='tanh', selection='argmax',
                    sources={file: hashlib.sha256((ROOT / 'ai/models' / file).read_bytes()).hexdigest()
                             for file in ('cem.json', 'ppo.zip')},
                    exports={'PolicyData.h': hashlib.sha256(header.read_bytes()).hexdigest()})
    (output / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=ROOT / 'ai/models/native')
    export(parser.parse_args().output)


if __name__ == '__main__':
    main()
